AsyncApi files-scenarios link
asyncapi/fluffy-robot pull request #27
Opened 2021-06-30 13:34 UTC by NektariosFifes

**Description**

- ...
- ...
- ...

**Related issue(s)**

2021-07-04 19:51 UTC, NektariosFifes commented
@jonaslagoni

2021-07-05 11:01 UTC, jonaslagoni requested changes
Just some general comments and suggestions 🙂 👍 

Be very careful about creating function names such as `verifyInput_ParseAndLinkFiles` as they can grow undesirably long 😄

2021-07-05 11:15 UTC, NektariosFifes commented on src/parser/scenarioParserAndConnector.js
> +  parserContext.ready = false;
its just a leftover from smth else i had done previously i will remove it

2021-07-05 11:18 UTC, NektariosFifes commented on src/parser/scenarioParserAndConnector.js
> +  const parserContext = this;
i was just for declaring the variable at the start of the function and implying the role of the variable but it is not needed. i will remove

2021-07-08 12:35 UTC, jonaslagoni approved these changes
👍

2021-07-08 12:43 UTC, merged